### ISSUE TITLE
 Core dump

### ISSUE THREAD

**Issue by ruijtunes** [libretro/beetle-vb-libretro#69] opened 2021-07-17 10:44 UTC
After the nightly from 9th of July this core stopped working.
So it must be one oft the pull requests: #64, #66, #67.
Tested on Wii u.

**Comment by twinaphex** [comment] 2021-07-17 16:02
Do a bisect to check which PR it was.

**Comment by ruijtunes** [comment] 2021-07-17 18:43
Sorry but i don't know how to do it. I cannot compile the code. I can however test a trial version if it is useful.

**Comment by twinaphex** [comment] 2021-07-18 23:52
Then learn it. This is completely unhelpful otherwise.

**Comment by twinaphex** [comment] 2021-07-18 23:53
@negativeExponent So what are we going to do here? There is a regression, he doesn't know how to bisect, how to proceed now? It's concerning to me that as a result of these changes, it no longer works on WiiU.

**Comment by twinaphex** [comment] 2021-07-19 00:02
@ruijtunes Are you able to post a screenshot of the crash dump when this happens?

**Comment by negativeExponent** [comment] 2021-07-19 00:12
just revert all my work. imdone tracking down and fixing issues. read my
request in one of my tags

**Comment by Ploggy** [comment] 2021-07-19 00:33
![20210719_013101](https://user-images.githubusercontent.com/1160255/126087230-de911fc5-e1dd-434f-bb57-64f8b1a094e1.jpg)

**Comment by twinaphex** [comment] 2021-07-19 00:44
Thanks @Ploggy.

**Comment by twinaphex** [comment] 2021-07-19 00:45
My guess based on that stack dump (since it refers to Blip Buffer) is that it could be this PR -

https://github.com/libretro/beetle-vb-libretro/pull/67

but regardless of which PR it is, it would be better if instead of reverting we just fix the fundamental issue that causes the crash on WiiU.

**Comment by twinaphex** [comment] 2021-07-19 00:48
Another observation in this PR -

https://github.com/libretro/beetle-vb-libretro/pull/67/commits/3ebc52a4f4a76d100ed9840aae8da08600b8874f

The two Blip Buffers are no longer pointers, yet we still use realloc on the buffers? Why are we still using dynamic memory allocation on stack-allocated buffers? Methinks these are remnants that should be rewritten now that it's no longer on the heap.

**Comment by twinaphex** [comment] 2021-07-19 00:58
```
/d/git/libretro-super/libretro-mednafen_vb/libretro.cpp:static Blip_Buffer sbuf[2];
```

This was also not removed from libretro.cpp except that it serves no purpose anymore. I'm going to be reverting PR #67 in the here and now. There is a high likelihood it will fix this issue.

**Comment by twinaphex** [comment] 2021-07-19 00:59
Reverted PR #67, WiiU people let me know if it is fixed now in the upcoming nightlies.

**Comment by QuarkTheAwesome** [comment] 2021-07-19 02:08
Revering that PR seems to have fixed it, tested working w/ a local build.

**Comment by ruijtunes** [comment] 2021-07-19 19:11
Tested with the latest buil from the buildbot and I can confirm it works on a WiiU.

**Closed** 2021-07-20 03:01 UTC
